/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller
import org.scalameter.withWarmer
import org.scalameter.Warmer
import org.scalameter.measure
import org.scalameter.Warmer.Default
import scala.collection.parallel.CollectionConverters._
import scala.util.Random


object App {
  def main(args: Array[String]): Unit = {

    val mat1 = new MatrizOps()

    //matrices 2x2
    val m1 = mat1.matrizAlAzar(2, 5)
    val m2 = mat1.matrizAlAzar(2, 5)
    

    //matrices 4x4
    val m3 = mat1.matrizAlAzar(4, 3)
    val m4 = mat1.matrizAlAzar(4, 3)

    //matrices 8x8
    val m5 = mat1.matrizAlAzar(8, 4)
    val m6 = mat1.matrizAlAzar(8, 4)

    //matrices 16x16
    val m7 = mat1.matrizAlAzar(16, 5)
    val m8 = mat1.matrizAlAzar(16, 5)

    //matrices 32x32
    val m9 = mat1.matrizAlAzar(32, 4)
    val m10 = mat1.matrizAlAzar(32, 4)


    // 10 Pruebas para la función Strassen
    /*def pruebas(): Unit = {

      println("Multiplicacion Strassen 32x32")
      println("Matriz 1: ")
      m9.foreach(row => println(row))
      println("Matriz 2: ")
      m10.foreach(row => println(row))
      println("Resultado: ")
      (mat1.multStrassen(m9, m10)).foreach(row => println(row))
      val comp9 = mat1.compararAlgoritmos(mat1.multStrassen, mat1.multStrassenPar)(m9, m10)
      println("Tiempo de ejecución de Strassen: " + comp9(0))
      println("Tiempo de ejecución de Strassen Paralelo: " + comp9(1))

      println("Multiplicacion Strassen 32x32")
      println("Matriz 1: ")
      m10.foreach(row => println(row))
      println("Matriz 2: ")
      m9.foreach(row => println(row))
      println("Resultado: ")
      (mat1.multStrassen(m10, m9)).foreach(row => println(row))
      val comp10 = mat1.compararAlgoritmos(mat1.multStrassen, mat1.multStrassenPar)(m10, m9)
      println("Tiempo de ejecución de Strassen: " + comp10(0))
      println("Tiempo de ejecución de Strassen Paralelo: " + comp10(1))

    }*/

    // Prueba de diferencia de tiempo para el producto punto 
    def pruebasProductoPunto(): Unit = {
      val v1 = mat1.vectorAlAzar(10000000,10)
      val v2 = mat1.vectorAlAzar(10000000,10)
      val comp = mat1.compararProdPunto(mat1.prodPunto, mat1.prodPuntoParD)(v1, v2)
      println("Producto Punto (1000):")
      println("Vector 1: " + v1.mkString(" "))
      println("Vector 2: " + v2.mkString(" "))
      println("Resultado Producto Punto:" + mat1.prodPunto(v1, v2))
      println("Tiempo de ejecución de Producto Punto " + comp(0))
      println("Tiempo de ejecución de Producto Punto Paralelo " + comp(1))
      println("Aceleración: " + comp(2))
    }

    //Pruebas - Comparación de desempeño de algoritmo de multiplicación estandar y su versión paralela
    /*def pruebasMultiplicacionEstandar(): Unit = {
      println("1. Multiplicacion Estandar 32x32")
      println("Matriz 1: ")
      val E1 = mat1.matrizAlAzar(32, 32)
      E1.foreach(row => println(row))
      println("Matriz 2: ")
      val E2 = mat1.matrizAlAzar(32, 32)
      E2.foreach(row => println(row))
      val comp = mat1.compararAlgoritmos(mat1.multMatrizEstandarSec, mat1.multMatrizEstandarPar)(E1, E2)
      println("Tiempo de ejecución de Multiplicación Estandar: " + comp(0))
      println("Tiempo de ejecución de Multiplicación Estandar Paralelo: " + comp(1))

      println("2. Multiplicacion Estandar 16x16")
      println("Matriz 1: ")
      val E3 = mat1.matrizAlAzar(16, 16)
      E3.foreach(row => println(row))
      println("Matriz 2: ")
      val E4 = mat1.matrizAlAzar(16, 16)
      E4.foreach(row => println(row))
      val comp1 = mat1.compararAlgoritmos(mat1.multMatrizEstandarSec, mat1.multMatrizEstandarPar)(E3, E4)
      println("Tiempo de ejecución de Multiplicación Estandar: " + comp1(0))
      println("Tiempo de ejecución de Multiplicación Estandar Paralelo: " + comp1(1))

      println("3. Multiplicacion Estandar 4x4")
      println("Matriz 1: ")
      val E5 = mat1.matrizAlAzar(4, 4)
      E5.foreach(row => println(row))
      println("Matriz 2: ")
      val E6 = mat1.matrizAlAzar(4, 4)
      E6.foreach(row => println(row))
      val comp2 = mat1.compararAlgoritmos(mat1.multMatrizEstandarSec, mat1.multMatrizEstandarPar)(E5, E6)
      println("Tiempo de ejecución de Multiplicación Estandar: " + comp2(0))
      println("Tiempo de ejecución de Multiplicación Estandar Paralelo: " + comp2(1))
    }*/
  
    /*def pruebasRec(): Unit = {

      val mt1 = mat1.matrizAlAzar(32, 4)
      val mt2 = mat1.matrizAlAzar(32, 4)

      println("Multiplicacion recursiva 32x32")
      println("Matriz 1: ")
      mt1.foreach(row => println(row))
      println("Matriz 2: ")
      mt2.foreach(row => println(row))
      println("Resultado: ")
      (mat1.multMatrizRec(mt1, mt2)).foreach(row => println(row))
      val compa1 = mat1.compararAlgoritmos(mat1.multMatrizRec, mat1.multMatrizRecPar)(mt1, mt2)
      println("Tiempo de ejecución de recursiva: " + compa1(0))
      println("Tiempo de ejecución de recursiva Paralelo: " + compa1(1))
      println("Aceleracion: " + compa1(2))

      println("Multiplicacion recursiva 32x32")
      println("Matriz 1: ")
      mt2.foreach(row => println(row))
      println("Matriz 2: ")
      mt1.foreach(row => println(row))
      println("Resultado: ")
      (mat1.multMatrizRec(mt2, mt1)).foreach(row => println(row))
      val compa2 = mat1.compararAlgoritmos(mat1.multMatrizRec, mat1.multMatrizRecPar)(mt2, mt1)
      println("Tiempo de ejecución de recursiva: " + compa2(0))
      println("Tiempo de ejecución de recursiva Paralelo: " + compa2(1))
      println("Aceleracion: " + compa2(2))
    }*/

    /*pruebasMultiplicacionEstandar()
    pruebasProductoPunto()
    pruebas()
    pruebasRec()*/
    pruebasProductoPunto()
  }

  def greeting(): String = "Hello, world!"
}
